import numpy as np

Fighter = {'velocity': 6,
           'acc': 0.3,
           'av': 2,
           'energy': 500,
           'health': 125,
           'height': 50,
           'width': 50,
           'range': 20000,
           'turrets': [],
           'turret_pos': [],
           'primary': 2,
           'secondary': 1,
           'mine': 0,
           'utility': 1,
           'cargo_cap': 50,
           'cost': {"Iron": 100, "Nickel": 25, "Platinum": 25, "Gold": 5},
           'name': "Fighter"}

Sprinter = {'velocity': 7,
            'acc': 0.5,
            'av': 1.75,
            'energy': 250,
            'health': 100,
            'height': 30,
            'width': 30,
            'range': 15000,
            'turrets': [],
            'turret_pos': [],
            'primary': 1,
            'secondary': 1,
            'mine': 0,
            'utility': 1,
            'cargo_cap': 10,
            'cost': {"Iron": 50, "Nickel": 30, "Platinum": 30, "Gold": 10},
            'name': "Sprinter"}

Frigate = {'velocity': 3.5,
           'acc': 0.25,
           'av': 0.5,
           'energy': 600,
           'health': 400,
           'height': 80,
           'width': 80,
           'range': 30000,
           'turrets': ['PDC'],
           'turret_pos': [np.array([0, 0])],
           'primary': 1,
           'secondary': 1,
           'mine': 1,
           'utility': 1,
           'cargo_cap': 1000,
           'cost': {"Iron": 300, "Nickel": 50, "Platinum": 40, "Gold": 30},
           'name': "Frigate"}

Destroyer = {'velocity': 3,
             'acc': 0.15,
             'av': 0.25,
             'energy': 5000,
             'health': 1200,
             'height': 150,
             'width': 150,
             'range': 50000,
             'turrets': ['Rail', 'PDC', 'PDC'],
             'turret_pos': [np.array([0, 0]), np.array([0, 41]), np.array([0, -41])],
             'primary': 2,
             'secondary': 2,
             'mine': 1,
             'utility': 3,
             'cargo_cap': 300,
             'cost': {"Iron": 300, "Nickel": 50, "Platinum": 40, "Gold": 30},
             'name': "Destroyer"}

ShipNames = [Fighter, Sprinter, Frigate, Destroyer]

